version: "3.7"

services:
  aws_management_prod:
    image: $IMAGE:$TAG
    build:
      context: .
      target: prod
    ports:
      - $HOST_PORT:8000
    env_file:
      - .env.prod
    restart: unless-stopped
