version: "3.7"

services:
  aws_management_dev:
    image: aws_management:dev
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
    environment:
      - DEBUG=true
    ports:
      - 8000:8000
    env_file:
      - .env
