# Generated by Django 4.2.6 on 2023-10-16 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('aws_access_key_id', models.CharField(max_length=50)),
                ('aws_secret_access_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RDSInstance',
            fields=[
                ('db_identifier', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('db_engine', models.CharField(max_length=20)),
                ('db_status', models.CharField(max_length=20)),
                ('db_instance_class', models.CharField(max_length=20)),
                ('creation_time', models.DateTimeField()),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.awsaccount')),
            ],
        ),
        migrations.CreateModel(
            name='EC2Instance',
            fields=[
                ('instance_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('instance_name', models.CharField(max_length=100)),
                ('instance_state', models.CharField(max_length=20)),
                ('instance_type', models.CharField(max_length=20)),
                ('platform', models.CharField(max_length=20)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('launch_time', models.DateTimeField()),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.awsaccount')),
            ],
        ),
    ]
