# Generated by Django 4.2.6 on 2023-10-23 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('aws_access_key_id', models.CharField(max_length=50)),
                ('aws_secret_access_key', models.CharField(help_text='This field is not visible for security reasons', max_length=100)),
            ],
            options={
                'verbose_name': 'AWS Account',
                'verbose_name_plural': 'AWS Accounts',
            },
        ),
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('action', models.CharField(choices=[('up', 'UP'), ('down', 'DOWN')], max_length=5)),
                ('minute', models.CharField(default='0', help_text='min (0-59) or * for every minute', max_length=10)),
                ('hour', models.CharField(default='0', help_text='hour (0-23) or *  for every hour', max_length=10)),
                ('day_of_month', models.CharField(default='*', help_text='1-31 or * for all day of month', max_length=10)),
                ('month', models.CharField(default='*', help_text='1-12 or * for all months', max_length=10)),
                ('day_of_week', models.CharField(default='*', help_text='0-6 (sunday to saturday) or * for all week days', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.awsaccount')),
            ],
            options={
                'verbose_name': 'Cron Job',
                'verbose_name_plural': 'Cron Jobs',
                'ordering': ['-active'],
            },
        ),
        migrations.CreateModel(
            name='RDSInstance',
            fields=[
                ('db_identifier', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('db_engine', models.CharField(max_length=20)),
                ('db_status', models.CharField(max_length=20)),
                ('db_instance_class', models.CharField(max_length=20)),
                ('creation_time', models.DateTimeField()),
                ('managed', models.BooleanField(default=False, help_text='If selected cronjob can manage this resource')),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.awsaccount')),
            ],
            options={
                'verbose_name': 'AWS RDS Instance',
                'verbose_name_plural': 'AWS RDS Instances',
                'ordering': ['-creation_time'],
                'default_related_name': 'rds_instances',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('from_email', models.EmailField(max_length=254)),
                ('recipient_list', models.TextField(help_text='separated with a comma (,)')),
                ('server', models.CharField(default='smtp.gmail.com', max_length=50)),
                ('port', models.IntegerField(default=587)),
                ('auth_user', models.EmailField(max_length=254)),
                ('auth_password', models.CharField(help_text='This field is not visible for security reasons', max_length=100)),
                ('tls', models.BooleanField(default=True)),
                ('ssl', models.BooleanField(default=False)),
                ('only_failed_jobs', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.awsaccount')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'default_related_name': 'notification_configs',
            },
        ),
        migrations.CreateModel(
            name='EC2Instance',
            fields=[
                ('instance_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('instance_name', models.CharField(max_length=100)),
                ('instance_state', models.CharField(max_length=20)),
                ('instance_type', models.CharField(max_length=20)),
                ('platform', models.CharField(max_length=20)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('launch_time', models.DateTimeField()),
                ('managed', models.BooleanField(default=False, help_text='If selected cronjob can manage this resource')),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.awsaccount')),
            ],
            options={
                'verbose_name': 'AWS EC2 Instance',
                'verbose_name_plural': 'AWS EC2 Instances',
                'ordering': ['-launch_time'],
                'default_related_name': 'ec2_instances',
            },
        ),
        migrations.CreateModel(
            name='CronJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(default='', max_length=200)),
                ('log_data', models.TextField()),
                ('success', models.BooleanField(default=True)),
                ('cronjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cronjob')),
            ],
            options={
                'verbose_name': 'Job Log',
                'verbose_name_plural': 'Job Logs',
                'ordering': ['-time'],
            },
        ),
    ]
