# Generated by Django 4.2.6 on 2023-10-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2instance',
            name='managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rdsinstance',
            name='managed',
            field=models.BooleanField(default=False),
        ),
    ]
