# Generated by Django 4.2.6 on 2023-10-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ec2instance_managed_rdsinstance_managed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awsaccount',
            options={'verbose_name': 'AWS Account', 'verbose_name_plural': 'AWS Accounts'},
        ),
        migrations.AlterModelOptions(
            name='ec2instance',
            options={'verbose_name': 'EC2 Instance', 'verbose_name_plural': 'EC2 Instances'},
        ),
        migrations.AlterModelOptions(
            name='rdsinstance',
            options={'verbose_name': 'RDS Instance', 'verbose_name_plural': 'RDS Instances'},
        ),
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('up', 'UP'), ('down', 'DOWN')], max_length=5)),
                ('cron_expression', models.CharField(max_length=20)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.awsaccount')),
            ],
            options={
                'verbose_name': 'CronJob',
                'verbose_name_plural': 'CronJobs',
            },
        ),
    ]
