# Generated by Django 4.2.6 on 2023-10-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_awsaccount_options_alter_ec2instance_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronjob',
            old_name='cron_expression',
            new_name='cron_schedule',
        ),
    ]
