# Generated by Django 4.2.6 on 2023-10-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_cron_expression_cronjob_cron_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronjob',
            options={'verbose_name': 'Cron Job', 'verbose_name_plural': 'Cron Jobs'},
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='cron_schedule',
        ),
        migrations.AddField(
            model_name='cronjob',
            name='day_of_month',
            field=models.CharField(default='*', max_length=10),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='day_of_week',
            field=models.CharField(default='*', max_length=10),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='hour',
            field=models.IntegerField(default=0, help_text='min(0-23)'),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='minute',
            field=models.IntegerField(default=0, help_text='min(0-59)'),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='month',
            field=models.CharField(default='*', max_length=10),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
