# Generated by Django 4.2.6 on 2023-10-18 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cronjob_options_remove_cronjob_cron_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='day_of_month',
            field=models.CharField(default='*', help_text='1-31 or * for all day of month', max_length=10),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='day_of_week',
            field=models.CharField(default='*', help_text='0-6 (sunday to saturday) or * for all week days', max_length=10),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='hour',
            field=models.IntegerField(default=0, help_text='hour (0-23)', validators=[django.core.validators.MinValueValidator(0, message='Hours should be at least 0.'), django.core.validators.MaxValueValidator(23, message='Hours should be at most 23.')]),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='minute',
            field=models.IntegerField(default=0, help_text='min (0-59)', validators=[django.core.validators.MinValueValidator(0, message='Minutes should be at least 0.'), django.core.validators.MaxValueValidator(59, message='Minutes should be at most 59.')]),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='month',
            field=models.CharField(default='*', help_text='1-12 or * for all months', max_length=10),
        ),
    ]
