# Generated by Django 4.2.6 on 2023-10-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_awsaccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
