# Generated by Django 4.2.6 on 2023-10-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cronjob_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cronjob',
            old_name='status',
            new_name='active',
        ),
    ]
