# Generated by Django 4.2.6 on 2023-10-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_cronjob_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ec2instance',
            options={'default_related_name': 'ec2_instances', 'verbose_name': 'EC2 Instance', 'verbose_name_plural': 'EC2 Instances'},
        ),
        migrations.AlterModelOptions(
            name='rdsinstance',
            options={'default_related_name': 'rds_instances', 'verbose_name': 'RDS Instance', 'verbose_name_plural': 'RDS Instances'},
        ),
    ]
