# Generated by Django 4.2.6 on 2023-10-18 22:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_ec2instance_options_alter_rdsinstance_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('log_data', models.TextField(max_length=200)),
                ('cronjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cronjob')),
            ],
            options={
                'verbose_name': 'CronJobLog',
                'verbose_name_plural': 'CronJobLogs',
            },
        ),
    ]
