# Generated by Django 4.2.6 on 2023-10-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cronjoblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronjoblog',
            options={'ordering': ['-time'], 'verbose_name': 'CronJobLog', 'verbose_name_plural': 'CronJobLogs'},
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='hour',
            field=models.IntegerField(default=0, help_text='hour (0-23) or *  for every hour'),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='minute',
            field=models.IntegerField(default=0, help_text='min (0-59) or * for every minute'),
        ),
    ]
