# Generated by Django 4.2.6 on 2023-10-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_cronjoblog_options_alter_cronjob_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='hour',
            field=models.CharField(default='0', help_text='hour (0-23) or *  for every hour', max_length=10),
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='minute',
            field=models.CharField(default='0', help_text='min (0-59) or * for every minute', max_length=10),
        ),
    ]
