# Generated by Django 4.2.6 on 2023-10-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_cronjob_hour_alter_cronjob_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjoblog',
            name='log_data',
            field=models.TextField(max_length=500),
        ),
    ]
