# Generated by Django 4.2.6 on 2023-10-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_cronjoblog_log_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjoblog',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cronjoblog',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
