# Generated by Django 4.2.6 on 2023-10-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_cronjoblog_description_cronjoblog_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjoblog',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
