# Generated by Django 4.2.6 on 2023-10-19 23:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_cronjoblog_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronjoblog',
            options={'ordering': ['-time'], 'verbose_name': 'Job Log', 'verbose_name_plural': 'Job Logs'},
        ),
        migrations.AlterModelOptions(
            name='ec2instance',
            options={'default_related_name': 'ec2_instances', 'verbose_name': 'AWS EC2 Instance', 'verbose_name_plural': 'AWS EC2 Instances'},
        ),
        migrations.AlterModelOptions(
            name='rdsinstance',
            options={'default_related_name': 'rds_instances', 'verbose_name': 'AWS RDS Instance', 'verbose_name_plural': 'AWS RDS Instances'},
        ),
        migrations.AlterField(
            model_name='cronjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
