# Generated by Django 4.2.6 on 2023-10-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_cronjob_options_alter_ec2instance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2instance',
            name='managed',
            field=models.BooleanField(default=False, help_text='If selected cronjob can manage this resource'),
        ),
        migrations.AlterField(
            model_name='rdsinstance',
            name='managed',
            field=models.BooleanField(default=False, help_text='If selected cronjob can manage this resource'),
        ),
    ]
