# Generated by Django 4.2.6 on 2023-10-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_ec2instance_managed_alter_rdsinstance_managed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_password', models.CharField(help_text='This field is not visible for security reasons', max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.awsaccount')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'default_related_name': 'notification_config',
            },
        ),
    ]
