# Generated by Django 4.2.6 on 2023-10-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('from_email', models.EmailField(max_length=254)),
                ('recipient_list', models.TextField(help_text='separated with a comma (,)')),
                ('auth_user', models.EmailField(max_length=254)),
                ('auth_password', models.CharField(help_text='This field is not visible for security reasons', max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.awsaccount')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'default_related_name': 'notification_config',
            },
        ),
    ]
