# Generated by Django 4.2.6 on 2023-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(default='smtp.gmail.com', max_length=100),
        ),
    ]
