# Generated by Django 4.2.6 on 2023-10-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_notification_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='notification',
            name='server',
            field=models.CharField(default='smtp.gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
